apiVersion: apps/v1
kind: Deployment
metadata:
  name: first-replicaset
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      a: america
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        a: america
    spec:
      containers:
      - name: nginx
        image: httpd
        ports:
        - containerPort: 80  # Expose the container port
