apiVersion: apps/v1
kind: Deployment
metadata:
  name: first-replicaset
  namespace: default
spec:
  replicas: 5
  selector:
    matchLabels:
      a: america
  template:
    metadata:
      labels:
        a: america
    spec:
      containers:
      - name: container-1
        image: httpd
        ports:
        - containerPort: 80  
